name: Continuous Integration

on:
  workflow_dispatch:
  push:

env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
jobs:
  check-app:
    runs-on: ubuntu-latest   
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.6
    
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest 

    - name: Run Staticcheck lint
      uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"
         
    - name: Run Revive lint
      uses: morphy2k/revive-action@v2

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Run reviewdog github-check
      continue-on-error: true      
      run: reviewdog -reporter=github-check  
