name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:
      
jobs:
  check-app:
    runs-on: ubuntu-latest   
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.6
    
    - name: Run staticcheck with Reviewdog
      uses: reviewdog/action-staticcheck@v1
      with:
        level: error
        reporter: github-pr-review
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run misspell
      uses: reviewdog/action-misspell@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        locale: "US"

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        golangci_lint_flags: "--enable-all --exclude-use-default=false"
        github_token: ${{ secrets.GITHUB_TOKEN }}