name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:
      
jobs:
  check-app:
    runs-on: ubuntu-latest   
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.6
    
    - name: Run staticcheck with Reviewdog
      uses: reviewdog/action-staticcheck@v1
      with:
        level: error
        reporter: github-pr-review
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run revive with Reviewdog
      uses: reviewdog/action-revive@v1
      with:
        level: error
        reporter: github-pr-review
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
